describe('twoToEleven', function() {
  it('selects random number between two and eleven', function() {
    expect(twoToEleven(4)).to.be.a('number');
  });
});


testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttesttesttest
